export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).end();

  const {
    businessName,
    industry,
    location,
    services,
    vibe,
    colors,
    hasLogo,
    phone,
    email,
    address,
    social,
    extraNotes
  } = req.body;

  if (!businessName || !industry || !services) {
    return res.status(400).json({ error: 'Missing required fields' });
  }

  const prompt = `You are an expert web designer building a single-file HTML website for a local small business. Build a complete, professional, modern website as a single self-contained HTML file.

CLIENT BRIEF:
- Business Name: ${businessName}
- Industry: ${industry}
- Location: ${location || 'Not provided'}
- Services: ${services}
- Vibe/Style: ${vibe || 'Modern and professional'}
- Color Preferences: ${colors || 'Use colors that suit the industry'}
- Has Logo: ${hasLogo || 'No'}
- Phone: ${phone || 'Not provided'}
- Email: ${email || 'Not provided'}
- Address: ${address || 'Not provided'}
- Social Media: ${social || 'Not provided'}
- Extra Notes: ${extraNotes || 'None'}

TECHNICAL REQUIREMENTS:
- Single HTML file, completely self-contained (no external files except Google Fonts + GSAP CDN)
- Mobile responsive
- Use Google Fonts appropriate to the vibe
- Use GSAP 3.12.5 + ScrollTrigger for scroll reveal animations
- CSS custom properties for colors (--primary, --primary-dark, --accent)
- Smooth scroll behavior
- Professional nav with mobile hamburger menu

SECTIONS TO INCLUDE (in this order):
1. Nav — logo placeholder (text-based), links, CTA button
2. Hero — strong headline, subheadline, 2 CTA buttons (primary + ghost), trust indicators
3. Services — grid of service cards with icons (use simple CSS shapes or unicode symbols)
4. About/Why Choose Us — 2-col layout with stats or key points
5. Testimonials — 2-3 fake but realistic reviews appropriate to the industry and location
6. Contact — form (name, email, phone, message) + contact info sidebar
7. Footer — links, contact, copyright

DESIGN RULES:
- No placeholder lorem ipsum — write real copy based on the business info provided
- Testimonials must feel real and local (use local-sounding names)
- Service cards must list the actual services provided
- Hero headline must be punchy and benefit-focused
- If no colors provided, pick a palette that fits the industry (cleaning = fresh blues/greens, food = warm reds/oranges, etc.)
- Use Web3Forms for the contact form with key "YOUR_WEB3FORMS_KEY" as placeholder
- Add a comment at the top: <!-- Generated by FJMedia AI for ${businessName} -->

Output ONLY the complete HTML file. No explanation, no markdown fencing, just raw HTML starting with <!DOCTYPE html>.`;

  try {
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'x-api-key': process.env.ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01',
        'content-type': 'application/json'
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-6',
        max_tokens: 8000,
        messages: [{ role: 'user', content: prompt }]
      })
    });

    if (!response.ok) {
      const err = await response.text();
      console.error('Anthropic error:', err);
      return res.status(500).json({ error: 'AI generation failed' });
    }

    const data = await response.json();
    const html = data.content[0].text;

    res.json({ html, businessName });

  } catch (err) {
    console.error('Generate error:', err);
    res.status(500).json({ error: 'Server error' });
  }
}
